# Generated by Django 4.0.4 on 2022-05-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMBTI',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=10)),
                ('teamAddress', models.CharField(max_length=10)),
                ('createTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('memberId', models.AutoField(primary_key=True, serialize=False)),
                ('memberName', models.CharField(max_length=10)),
                ('MBTI', models.CharField(choices=[('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ESTJ', 'ESTJ'), ('ESFJ', 'ESFJ'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP'), ('ISTP', 'ISTP'), ('ISFP', 'ISFP')], max_length=4)),
                ('memberJoinDate', models.DateTimeField()),
            ],
        ),
    ]
